export const menuItems = [
  {
    id: 1,
    title: "Products",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 2,
    title: "Start Selling",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 3,
    title: "Tools and apps",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 4,
    title: "Pricing",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 5,
    title: "Resources",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 6,
    title: "Pro seller",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
  {
    id: 7,
    title: "Gelato Connect",
    submenu: [
      { id: 1, title: "Best Selling" },
      { id: 2, title: "Mens clothing" },
      { id: 3, title: "Women's clothing" },
      { id: 4, title: "Kids & baby clothing" },
      { id: 5, title: "Tote Bags" },
      { id: 6, title: "Wall art" },
      { id: 7, title: "Calendars" },
      { id: 8, title: "Cards" },
    ],
  },
];
